/******************************************************************************/
/*
* Question: #389 Find the Difference
* Given two strings s and t which consist of only lowercase letters.
* String t is generated by random shuffling string s and then add one more letter at a random position.
* Find the letter that was added in t.

Example: 
Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

*/
/*****************************************************************************/

#include <string>
#include <unordered_map>

using namespace std;

char findTheDifference(string s, string t) {
	unordered_map<char, int> table;
	char add;
	for (int i = 0; i < t.length(); i++)
	{
		table[t[i]]++;
	}
	for (int i = 0; i < s.length(); i++)
	{
		table[s[i]]--;
	}
	for (int i = 0; i < t.length(); i++)
	{
		if (table[t[i]] > 0)
		{
			add = t[i];
		}
	}
	return add;
}